"""Render the existing bilingual templates as crawlable English HTML.

The Chinese HTML and its data-en attributes remain the only page templates.
This mirrors the original language switch at build time, retaining all sections,
media, classes, IDs and scripts. No third-party build dependency is required.
"""
from html import escape
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin, urlsplit, urlunsplit

ORIGIN = "https://hboyjd.com"
PAGES = {"index.html": ("/", "/en/"), "about.html": ("/about.html", "/en/about.html")}
VOID = set("area base br col embed hr img input link meta param source track wbr".split())


def root_url(value):
    """Resolve template-relative assets against the original site root."""
    if not value or value.startswith(("#", "/")) or urlsplit(value).scheme:
        return value
    return "/" + value


def english_link(value):
    absolute = urlsplit(urljoin(ORIGIN + "/", value))
    if absolute.netloc != "hboyjd.com" or absolute.scheme not in ("https", "http"):
        return value
    path = {"/": "/en/", "/index.html": "/en/", "/about.html": "/en/about.html"}.get(absolute.path, absolute.path)
    return urlunsplit(("", "", path, absolute.query, absolute.fragment))


class EnglishPage(HTMLParser):
    def __init__(self, chinese_url, english_url):
        super().__init__(convert_charrefs=False)
        self.chinese_url = chinese_url
        self.english_url = english_url
        self.output = []
        self.skip_depth = 0
        self.select_first = None

    def handle_starttag(self, tag, attrs):
        self._start(tag, attrs, False)

    def handle_startendtag(self, tag, attrs):
        self._start(tag, attrs, True)

    def _start(self, tag, attrs, closed):
        if self.skip_depth:
            if tag not in VOID and not closed:
                self.skip_depth += 1
            return
        attrs = dict(attrs)
        translated = attrs.get("data-en")
        if tag == "html":
            attrs["lang"] = "en"
        if tag == "select":
            self.select_first = attrs.get("data-en-first")
        if tag == "option" and self.select_first is not None:
            translated = self.select_first
            self.select_first = None
        for attr in ("placeholder", "alt", "title", "aria-label"):
            if attrs.get("data-en-" + attr):
                attrs[attr] = attrs["data-en-" + attr]
        if tag == "meta":
            if translated:
                attrs["content"] = translated
            prop = attrs.get("property")
            if prop == "og:url":
                attrs["content"] = ORIGIN + self.english_url
            elif prop == "og:locale":
                attrs["content"] = "en_US"
            elif prop == "og:locale:alternate":
                attrs["content"] = "zh_CN"
        if tag == "link" and attrs.get("rel") == "canonical":
            attrs["href"] = ORIGIN + self.english_url
        elif tag == "a" and "lang-toggle" in attrs.get("class", "").split():
            attrs.update(href=self.chinese_url, hreflang="zh-CN", lang="zh-CN",
                         title="切换中文", **{"aria-label": "切换中文"})
        elif tag == "a" and attrs.get("href") and not attrs["href"].startswith("#"):
            attrs["href"] = english_link(attrs["href"])
        elif tag == "link" and attrs.get("rel") != "alternate" and "href" in attrs:
            attrs["href"] = root_url(attrs["href"])
        for attr in ("src", "poster", "data-src"):
            if attr in attrs:
                attrs[attr] = root_url(attrs[attr])
        if "srcset" in attrs:
            attrs["srcset"] = ", ".join(" ".join([root_url(parts[0])] + parts[1:])
                for parts in (item.strip().split() for item in attrs["srcset"].split(",")))
        classes = attrs.get("class", "").split()
        if "lang-zh" in classes:
            attrs["class"] = " ".join(c for c in classes if c != "active")
        elif "lang-en" in classes:
            attrs["class"] = " ".join(classes + ([] if "active" in classes else ["active"]))
        self.output.append("<" + tag + "".join(
            " " + key if value is None else ' ' + key + '="' + escape(value, quote=True) + '"'
            for key, value in attrs.items()) + (" />" if closed else ">"))
        if tag == "head":
            self.output.append("\n<!-- Generated by build_pages.py from the shared bilingual template; do not edit this file. -->")
        if translated is not None and tag not in VOID and not closed:
            self.output.append(escape(translated, quote=False))
            self.skip_depth = 1

    def handle_endtag(self, tag):
        if self.skip_depth:
            self.skip_depth -= 1
            if self.skip_depth:
                return
        if tag == "select":
            self.select_first = None
        self.output.append("</" + tag + ">")

    def handle_data(self, data):
        if not self.skip_depth:
            self.output.append(data)

    def handle_entityref(self, name):
        self.handle_data("&" + name + ";")

    def handle_charref(self, name):
        self.handle_data("&#" + name + ";")

    def handle_comment(self, data):
        self.handle_data("<!--" + data + "-->")

    def handle_decl(self, decl):
        self.handle_data("<!" + decl + ">")


def build_english(root):
    root = Path(root)
    (root / "en").mkdir(exist_ok=True)
    for name, (chinese_url, english_url) in PAGES.items():
        parser = EnglishPage(chinese_url, english_url)
        parser.feed((root / name).read_text(encoding="utf-8"))
        parser.close()
        (root / "en" / name).write_text("".join(parser.output), encoding="utf-8")
        print("built en/" + name + " from shared " + name)


if __name__ == "__main__":
    build_english(Path(__file__).resolve().parents[1])
